version: "3.9"
services:
  master_bot:
    build:
      context: .
      dockerfile: ./bot/master_bot/Dockerfile
    environment:
      - BINANCE_API_KEY=${BINANCE_API_KEY}
      - BINANCE_API_SECRET=${BINANCE_API_SECRET}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis

  worker_bot_1:
    build:
      context: .
      dockerfile: ./bot/worker_bot/Dockerfile
    environment:
      - STRATEGY_NAME=CandlePattern
      - PAIR=BTCUSDT
      - INTERVAL=1m
      - BINANCE_API_KEY=${BINANCE_API_KEY}
      - BINANCE_API_SECRET=${BINANCE_API_SECRET}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PYTHONUNBUFFERED=1
    depends_on:
      - redis

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  # db:
  #   image: postgres:latest
  #   environment:
  #     POSTGRES_USER: user
  #     POSTGRES_PASSWORD: my_secretpassword
  #     POSTGRES_DB: trading
  #   ports:
  #     - "5431:5432"